"""
Example script demonstrating specular point computation and switching algorithm.
Uses saved data for CYGNSS position and GPS tramnsmitter positions, and computes the 
specular point generated by each GPS/CYGNSS pair. 

Prints the percentage of time points where the top 4 GPS satellites selected by the switching 
algorithm match the top 4 GPS satellites from the reference data. The top 4 are selected by taking
the specular point trajectories with the highest RCG factor at each time point.

Then, at each time point, selects the specular point with the lowest error norm vs the reference
specular point trajectory, and plots the error norm over time.
"""

import numpy as np
import os
import matplotlib.pyplot as plt

from eosimutils.time import AbsoluteDateArray
from eosimutils.trajectory import StateSeries, PositionSeries
from eosimutils.base import ReferenceFrame, SurfaceType

from orbitpy.specular import get_specular_trajectory, get_topk_trajectories


def convert_datetime(np_dt):
    """Convert numpy datetime object to AbsoluteDateArray

    Args:
        np_dt (np.ndarray): Numpy datetime64 array.

    Returns:
        AbsoluteDateArray: Orbitpy AbsoluteDateArray object with the times from the datetime object
    """

    arr = np.atleast_1d(np_dt)

    if not np.issubdtype(arr.dtype, np.datetime64):
        raise TypeError("np_dt must be a numpy.datetime64 scalar or array")

    # Convert to millisecond precision ISO strings without timezone
    arr_ms = arr.astype("datetime64[ms]")
    iso = np.datetime_as_string(arr_ms, unit="ms", timezone="naive")
    iso_list = [str(iso)] if np.isscalar(iso) else iso.astype(str).tolist()

    return AbsoluteDateArray.from_dict(
        {
            "time_format": "GREGORIAN_DATE",
            "calendar_date": iso_list,
            "time_scale": "UTC",
        }
    )

# -------------
# READ IN DATA
# -------------

KM_TO_M = 1000.0
M_TO_KM = 1.0 / 1000.0

sat_number = "03"
ddm_num = 1
folder = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "cygnss_data", ""
)
ext = ".npy"

cyg_file = folder + "cygnss_spacecraft_trajectory.csv"
cyg_pos = data = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)*M_TO_KM
cyg_vel = data = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(4, 5, 6)
)*M_TO_KM

specular_file = folder + "specular_point_positions_ddm3.csv"
sp_pos = np.loadtxt(
    specular_file,
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)*M_TO_KM

ddm_timestamp_utc = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(0,),
    dtype="datetime64[ns]"
)

gps_ids = ["43", "44", "45", "48","50","51","52","53","55","56","57","58","59","61","62","64","65","67","68","69","70","71","72","73","74","75","76","77","78","79"]
output_list = []

for id in gps_ids:
    print(f"Processing GPS satellite PRN {id}...")

    gps_file = folder + "prn_" + id + "_trajectory.csv"
    gps_pos = np.genfromtxt(
        gps_file,
        delimiter=",",
        skip_header=1,
        usecols=(1, 2, 3),
        dtype=float,
        filling_values=np.nan
    )*M_TO_KM
    gps_vel = np.genfromtxt(
        gps_file,
        delimiter=",",
        skip_header=1,
        usecols=(4, 5, 6),
        dtype=float,
        filling_values=np.nan
    )*M_TO_KM


    # -----------------------------------
    # Process input into orbitpy objects
    # -----------------------------------

    # Create AbsoluteDateArray from ddm timestamps
    datearray = convert_datetime(ddm_timestamp_utc)

    # Create Stateseries from CYGNSS positions/velocities
    sc_stateseries = StateSeries(
        time=datearray, data=[cyg_pos, cyg_vel], frame=ReferenceFrame.get("ITRF")
    )

    # Create Stateseries from GPS positions/velocities
    tx_stateseries = StateSeries(
        time=datearray, data=[gps_pos, gps_vel], frame=ReferenceFrame.get("ITRF")
    )

    # Create PositionSeries from specular point positions
    sp_posseries_ref = PositionSeries(
        time=datearray, data=sp_pos, frame=ReferenceFrame.get("ITRF")
    )

    # Compute specular points using ellipsoidal Earth model
    sp_posseries, rcg_factor_ellipsoidal = get_specular_trajectory(
        transmitter_states_itrf=tx_stateseries,
        receiver_states_itrf=sc_stateseries,
        times=datearray,
        surface=SurfaceType.WGS84,
    )

    output_list.append((sp_posseries, rcg_factor_ellipsoidal))

# ------------------------------
# Calculate smallest error
# ------------------------------
gps_ids_int = [int(id) for id in gps_ids]

output, topk = get_topk_trajectories(
    traj_list=output_list,
    k=4,
    ids=gps_ids_int,
)
topk_np = np.array(topk, dtype=int)

# Read in reference topk from file
topk_file = folder + "active_gps_numbers.txt"
topk = np.loadtxt(
    topk_file,
    delimiter=" ",
    dtype=int
)

# Compute percentage of time points where all four gps indices match the reference data
same = np.sort(topk_np, axis=1) == np.sort(topk, axis=1)
row_equal = same.all(axis=1)
percentage = 100.0 * row_equal.mean()
print(f"Percentage of time points where computed topk matches reference: {percentage:.2f}%")

# Among the computed specular point trajectories, take
# the specular point with the lowest error norm at each time point
# vs the reference specular point trajectory, and plot the error norm over time
norm_lists = []
for output in output_list:
    sp_posseries = output[0]
    diff = sp_posseries_ref - sp_posseries
    norms = np.linalg.norm(diff.data[0], axis=1)
    norm_lists.append(norms)

norms = np.min(np.stack(norm_lists), axis=0)

plt.figure()
plt.plot(datearray.ephemeris_time, norms)
plt.xlabel("Ephemeris Time (s)")
plt.ylabel("Error Norm (km)")
plt.title("Specular Location Error Norm, Ellipsoidal Earth")
plt.show()
