"""
Example script demonstrating specular point computation and switching algorithm, which
can select the top (or top-k) specular point trajectories based on the range-corrected
gain factor. The trajectory of rank "k" corresponds to the specular point trajectory with
the k-th highest RCG factor at each time point, using data from any number of GPS trasmitters.

The simulation uses saved data for CYGNSS position and GPS transmitter positions, and computes the 
specular point generated by each GPS/CYGNSS pair. 

Prints the percentage of time points where all four of the top 4 GPS satellites selected by the switching 
algorithm match the top 4 GPS satellites from the reference data.

Then, at each time point, selects the specular point with the lowest error norm vs the reference
specular point trajectory, and plots the error norm over time.

Next, compares the trajectory of the specular point on the fourth channel from the CYGNSS data to
the trajectory of the specular point generated by the corresponding GPS satellite, chooosing
from among the top-four trajectories. The error norm vs the reference specular point trajectory
is plotted over time.
"""

import numpy as np
import os
import matplotlib.pyplot as plt

from eosimutils.time import AbsoluteDateArray
from eosimutils.trajectory import StateSeries, PositionSeries
from eosimutils.base import ReferenceFrame, SurfaceType
from eosimutils.state import CartesianState

from orbitpy.specular import get_specular_trajectory, get_topk_trajectories
from orbitpy.propagator import PropagatorFactory
from orbitpy.orbits import TwoLineElementSet

def get_first_idx(arr):
    """Get index of first non-naan row in numpy array"""

    mask = ~np.isnan(arr).all(axis=1)
    first_idx = np.argmax(mask)
    return first_idx

def convert_datetime(np_dt):
    """Convert numpy datetime object to AbsoluteDateArray

    Args:
        np_dt (np.ndarray): Numpy datetime64 array.

    Returns:
        AbsoluteDateArray: Orbitpy AbsoluteDateArray object with the times from the datetime object
    """

    arr = np.atleast_1d(np_dt)

    if not np.issubdtype(arr.dtype, np.datetime64):
        raise TypeError("np_dt must be a numpy.datetime64 scalar or array")

    # Convert to millisecond precision ISO strings without timezone
    arr_ms = arr.astype("datetime64[ms]")
    iso = np.datetime_as_string(arr_ms, unit="ms", timezone="naive")
    iso_list = [str(iso)] if np.isscalar(iso) else iso.astype(str).tolist()

    return AbsoluteDateArray.from_dict(
        {
            "time_format": "GREGORIAN_DATE",
            "calendar_date": iso_list,
            "time_scale": "UTC",
        }
    )

# -------------
# READ IN DATA
# -------------

KM_TO_M = 1000.0
M_TO_KM = 1.0 / 1000.0

sat_number = "03"
ddm_num = 1
folder = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "cygnss_data", ""
)
ext = ".npy"

cyg_file = folder + "cygnss_spacecraft_trajectory.csv"
cyg_pos = data = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)*M_TO_KM
cyg_vel = data = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(4, 5, 6)
)*M_TO_KM

specular_file = folder + "specular_point_positions_ddm3.csv"
sp_pos = np.loadtxt(
    specular_file,
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)*M_TO_KM

ddm_timestamp_utc = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(0,),
    dtype="datetime64[ns]"
)

gps_ids = ["43", "44"]
output_list = []
tx_list = []
cyg_list = []
tx_starters = []
cyg_starters = []

for id in gps_ids:
    print(f"Processing GPS satellite PRN {id}...")

    gps_file = folder + "prn_" + id + "_trajectory.csv"
    gps_pos = np.genfromtxt(
        gps_file,
        delimiter=",",
        skip_header=1,
        usecols=(1, 2, 3),
        dtype=float,
        filling_values=np.nan
    )*M_TO_KM
    gps_vel = np.genfromtxt(
        gps_file,
        delimiter=",",
        skip_header=1,
        usecols=(4, 5, 6),
        dtype=float,
        filling_values=np.nan
    )*M_TO_KM


    # -----------------------------------
    # Process input into orbitpy objects
    # -----------------------------------

    # Create AbsoluteDateArray from ddm timestamps
    datearray = convert_datetime(ddm_timestamp_utc)

    # Create Stateseries from CYGNSS positions/velocities
    sc_stateseries = StateSeries(
        time=datearray, data=[cyg_pos, cyg_vel], frame=ReferenceFrame.get("ITRF")
    )

    cyg_list.append(sc_stateseries)

    # Create Stateseries from GPS positions/velocities
    tx_stateseries = StateSeries(
        time=datearray, data=[gps_pos, gps_vel], frame=ReferenceFrame.get("ITRF")
    )

    # Get first available state for transmitter
    tx_list.append(tx_stateseries)
    first_idx = get_first_idx(tx_stateseries.data[0])
    first_pos = tx_stateseries.data[0][get_first_idx(first_idx)]
    first_vel = tx_stateseries.data[1][get_first_idx(first_idx)]
    first_state = np.hstack((first_pos, first_vel))
    first_state = CartesianState.from_array(first_state, frame=ReferenceFrame.get("ITRF"), time=datearray[first_idx])
    tx_starters.append(first_state)

    # Get first available state for receiver (should always start at zero)
    first_idx = get_first_idx(sc_stateseries.data[0])
    first_pos = sc_stateseries.data[0][get_first_idx(first_idx)]
    first_vel = sc_stateseries.data[1][get_first_idx(first_idx)]
    first_state = np.hstack((first_pos, first_vel))
    first_state = CartesianState.from_array(first_state, frame=ReferenceFrame.get("ITRF"), time=datearray[first_idx])
    cyg_starters.append(first_state)

    # Create PositionSeries from specular point positions
    sp_posseries_ref = PositionSeries(
        time=datearray, data=sp_pos, frame=ReferenceFrame.get("ITRF")
    )

    # Compute specular points using ellipsoidal Earth model
    sp_posseries_ellipsoidal, rcg_factor_ellipsoidal = get_specular_trajectory(
        transmitter_states_itrf=tx_stateseries,
        receiver_states_itrf=sc_stateseries,
        times=datearray,
        surface=SurfaceType.WGS84,
    )

    output_list.append((sp_posseries_ellipsoidal, rcg_factor_ellipsoidal))

 
plt.figure()
plt.plot(datearray.ephemeris_time, tx_stateseries.data[0][:, 0], label="Reference Specular Point X")
plt.xlabel("Ephemeris Time (s)")
plt.ylabel("va")
plt.show()