"""
Example script demonstrating specular point computation and switching algorithm, which
can select the top (or top-k) specular point trajectories based on the range-corrected
gain factor. The trajectory of rank "k" corresponds to the specular point trajectory with
the k-th highest RCG factor at each time point, using data from any number of GPS trasmitters.

The simulation uses saved data for CYGNSS position and GPS transmitter positions, and computes the 
specular point generated by each GPS/CYGNSS pair. 

Prints the percentage of time points where all four of the top 4 GPS satellites selected by the switching 
algorithm match the top 4 GPS satellites from the reference data.

Then, at each time point, selects the specular point with the lowest error norm vs the reference
specular point trajectory, and plots the error norm over time.

Next, compares the trajectory of the specular point on the fourth channel from the CYGNSS data to
the trajectory of the specular point generated by the corresponding GPS satellite, chooosing
from among the top-four trajectories. The error norm vs the reference specular point trajectory
is plotted over time.
"""

import numpy as np
import os
import matplotlib.pyplot as plt

from eosimutils.time import AbsoluteDateArray
from eosimutils.trajectory import StateSeries, PositionSeries
from eosimutils.base import ReferenceFrame, SurfaceType

from orbitpy.specular import get_specular_trajectory, get_topk_trajectories


def convert_datetime(np_dt):
    """Convert numpy datetime object to AbsoluteDateArray

    Args:
        np_dt (np.ndarray): Numpy datetime64 array.

    Returns:
        AbsoluteDateArray: Orbitpy AbsoluteDateArray object with the times from the datetime object
    """

    arr = np.atleast_1d(np_dt)

    if not np.issubdtype(arr.dtype, np.datetime64):
        raise TypeError("np_dt must be a numpy.datetime64 scalar or array")

    # Convert to millisecond precision ISO strings without timezone
    arr_ms = arr.astype("datetime64[ms]")
    iso = np.datetime_as_string(arr_ms, unit="ms", timezone="naive")
    iso_list = [str(iso)] if np.isscalar(iso) else iso.astype(str).tolist()

    return AbsoluteDateArray.from_dict(
        {
            "time_format": "GREGORIAN_DATE",
            "calendar_date": iso_list,
            "time_scale": "UTC",
        }
    )

# -------------
# READ IN DATA
# -------------

KM_TO_M = 1000.0
M_TO_KM = 1.0 / 1000.0

sat_number = "03"
ddm_num = 1
folder = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "cygnss_data", ""
)
ext = ".npy"

cyg_file = folder + "cygnss_spacecraft_trajectory.csv"
cyg_pos = data = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)*M_TO_KM
cyg_vel = data = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(4, 5, 6)
)*M_TO_KM

specular_file = folder + "specular_point_positions_ddm3.csv"
sp_pos = np.loadtxt(
    specular_file,
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)*M_TO_KM

ddm_timestamp_utc = np.loadtxt(
    cyg_file,
    delimiter=",",
    skiprows=1,
    usecols=(0,),
    dtype="datetime64[ns]"
)

gps_ids = ["43", "44", "45", "48","50","51","52","53","55","56","57","58","59","61","62","64","65","67","68","69","70","71","72","73","74","75","76","77","78","79"]
output_list = []

for id in gps_ids:
    print(f"Processing GPS satellite PRN {id}...")

    gps_file = folder + "prn_" + id + "_trajectory.csv"
    gps_pos = np.genfromtxt(
        gps_file,
        delimiter=",",
        skip_header=1,
        usecols=(1, 2, 3),
        dtype=float,
        filling_values=np.nan
    )*M_TO_KM
    gps_vel = np.genfromtxt(
        gps_file,
        delimiter=",",
        skip_header=1,
        usecols=(4, 5, 6),
        dtype=float,
        filling_values=np.nan
    )*M_TO_KM


    # -----------------------------------
    # Process input into orbitpy objects
    # -----------------------------------

    # Create AbsoluteDateArray from ddm timestamps
    datearray = convert_datetime(ddm_timestamp_utc)

    # Create Stateseries from CYGNSS positions/velocities
    sc_stateseries = StateSeries(
        time=datearray, data=[cyg_pos, cyg_vel], frame=ReferenceFrame.get("ITRF")
    )

    # Create Stateseries from GPS positions/velocities
    tx_stateseries = StateSeries(
        time=datearray, data=[gps_pos, gps_vel], frame=ReferenceFrame.get("ITRF")
    )

    # Create PositionSeries from specular point positions
    sp_posseries_ref = PositionSeries(
        time=datearray, data=sp_pos, frame=ReferenceFrame.get("ITRF")
    )

    # Compute specular points using ellipsoidal Earth model
    sp_posseries_ellipsoidal, rcg_factor_ellipsoidal = get_specular_trajectory(
        transmitter_states_itrf=tx_stateseries,
        receiver_states_itrf=sc_stateseries,
        times=datearray,
        surface=SurfaceType.WGS84,
    )

    output_list.append((sp_posseries_ellipsoidal, rcg_factor_ellipsoidal))

# ------------------------------
# Calculate smallest error
# ------------------------------
gps_ids_int = [int(id) for id in gps_ids]

output, topk_list = get_topk_trajectories(
    traj_list=output_list,
    k=4,
    ids=gps_ids_int,
)
topk = np.array(topk_list, dtype=int)

# Read in reference topk from file
topk_file = folder + "active_gps_numbers.txt"
topk_ref = np.loadtxt(
    topk_file,
    delimiter=" ",
    dtype=int
)

# Compute percentage of time points where all four gps indices match the reference data
same = np.sort(topk, axis=1) == np.sort(topk_ref, axis=1)
row_equal = same.all(axis=1)
percentage = 100.0 * row_equal.mean()
print(f"Percentage of time points where computed topk matches reference: {percentage:.2f}%")

# Among the computed specular point trajectories, take
# the specular point with the lowest error norm at each time point
# vs the reference specular point trajectory, and plot the error norm over time
norm_lists = []
for output_item in output_list:
    sp_posseries = output_item[0]
    diff = sp_posseries_ref - sp_posseries
    norms = np.linalg.norm(diff.data[0], axis=1)
    norm_lists.append(norms)

norms = np.min(np.stack(norm_lists), axis=0)

plt.figure()
plt.plot(datearray.ephemeris_time, norms)
plt.xlabel("Ephemeris Time (s)")
plt.ylabel("Error Norm (km)")
plt.title("Specular Location Error Norm, Ellipsoidal Earth")


# Get the specular point trajectory from the computed top-four that matches
# the reference GPS satellite index for channel four at each time point.
# If the reference GPS is not present in the computed top-four, leave it as NaN.
# Then plot the error norm vs the reference specular point trajectory.

# GPS satellite indices for the reference channel-four specular point trajectory
channel_four_ref_indices = topk_ref[:, 3]

# Precompute all computed specular point positions as an array:
# shape = (num_gps, num_times, 3)
sp_all = np.stack([item[0].data[0] for item in output_list], axis=0)

num_times = len(channel_four_ref_indices)
matched_sp = np.full((num_times, 3), np.nan)

for i in range(num_times):
    ref_id = channel_four_ref_indices[i]

    # Only use this trajectory if the reference PRN is in the computed top-4 at this time
    if ref_id in topk[i]:
        gps_idx = gps_ids_int.index(ref_id)
        matched_sp[i] = sp_all[gps_idx, i]

matched_error = np.linalg.norm(sp_posseries_ref.data[0] - matched_sp, axis=1)

plt.figure()
plt.plot(datearray.ephemeris_time, matched_error)
plt.xlabel("Ephemeris Time (s)")
plt.ylabel("Error Norm (km)")
plt.title("Specular Location Error Norm for Reference Channel-Four GPS Match")
plt.show()